from snake.base import Pos, PointType, Map

wall1 = ((Pos(2, 2), PointType.WALL),
    (Pos(2, 3), PointType.WALL),
    (Pos(3, 3), PointType.WALL),
    (Pos(7, 3), PointType.WALL),
    (Pos(7, 5), PointType.WALL),
    (Pos(7, 4), PointType.WALL),
    (Pos(5, 7), PointType.WALL))

wall2 = ((Pos(1, 6), PointType.WALL),
        (Pos(1, 7), PointType.WALL),
        (Pos(1, 8), PointType.WALL),
        (Pos(1, 5), PointType.WALL),
        (Pos(9, 6), PointType.WALL),
        (Pos(9, 7), PointType.WALL),
        (Pos(9, 8), PointType.WALL),
        (Pos(9, 9), PointType.WALL),
        (Pos(9, 5), PointType.WALL),
        (Pos(6, 1), PointType.WALL),
        (Pos(7, 1), PointType.WALL),
        (Pos(8, 1), PointType.WALL),
        (Pos(5, 1), PointType.WALL),
        (Pos(4, 9), PointType.WALL),
        (Pos(6, 9), PointType.WALL),
        (Pos(5, 9), PointType.WALL))

wall3 = (
        # Walls
        (Pos(1, 6), PointType.WALL),
        (Pos(1, 7), PointType.WALL),
        (Pos(1, 8), PointType.WALL),
        (Pos(1, 9), PointType.WALL),
        (Pos(1, 10), PointType.WALL),
        (Pos(15, 6), PointType.WALL),
        (Pos(15, 7), PointType.WALL),
        (Pos(15, 8), PointType.WALL),
        (Pos(15, 9), PointType.WALL),
        (Pos(15, 10), PointType.WALL),
        (Pos(6, 1), PointType.WALL),
        (Pos(7, 1), PointType.WALL),
        (Pos(8, 1), PointType.WALL),
        (Pos(9, 1), PointType.WALL),
        (Pos(10, 1), PointType.WALL),
        (Pos(6, 15), PointType.WALL),
        (Pos(7, 15), PointType.WALL),
        (Pos(8, 15), PointType.WALL),
        (Pos(9, 15), PointType.WALL),
        (Pos(10, 15), PointType.WALL),
        # Food
        (Pos(4, 6), PointType.WALL),
        (Pos(4, 10), PointType.WALL),
        (Pos(6, 4), PointType.WALL),
        (Pos(10, 4), PointType.WALL),
        (Pos(6, 12), PointType.WALL),
        (Pos(10, 12), PointType.WALL),
        (Pos(12, 6), PointType.WALL),
        (Pos(12, 10), PointType.WALL),
        # Top-left
        (Pos(2, 2), PointType.WALL),
        (Pos(3, 2), PointType.WALL),
        (Pos(4, 2), PointType.WALL),
        (Pos(4, 3), PointType.WALL),
        (Pos(3, 3), PointType.WALL),
        (Pos(2, 3), PointType.WALL),
        (Pos(2, 4), PointType.WALL),
        (Pos(2, 4), PointType.WALL),
        (Pos(3, 4), PointType.WALL),
        (Pos(4, 4), PointType.WALL),
        # Top-right
        (Pos(2, 14), PointType.WALL),
        (Pos(3, 14), PointType.WALL),
        (Pos(4, 14), PointType.WALL),
        (Pos(4, 13), PointType.WALL),
        (Pos(3, 13), PointType.WALL),
        (Pos(2, 13), PointType.WALL),
        (Pos(2, 12), PointType.WALL),
        (Pos(3, 12), PointType.WALL),
        (Pos(4, 12), PointType.WALL),
        # Bottom-left
        (Pos(14, 2), PointType.WALL),
        (Pos(13, 2), PointType.WALL),
        (Pos(12, 2), PointType.WALL),
        (Pos(12, 3), PointType.WALL),
        (Pos(13, 3), PointType.WALL),
        (Pos(14, 3), PointType.WALL),
        (Pos(14, 4), PointType.WALL),
        (Pos(13, 4), PointType.WALL),
        (Pos(12, 4), PointType.WALL),
        # Bottom-right
        (Pos(14, 14), PointType.WALL),
        (Pos(13, 14), PointType.WALL),
        (Pos(12, 14), PointType.WALL),
        (Pos(12, 13), PointType.WALL),
        (Pos(13, 13), PointType.WALL),
        (Pos(14, 13), PointType.WALL),
        (Pos(14, 12), PointType.WALL),
        (Pos(13, 12), PointType.WALL),
        (Pos(12, 12), PointType.WALL),
        # Middle
        (Pos(9, 6), PointType.WALL),
        (Pos(9, 7), PointType.WALL),
        (Pos(9, 8), PointType.WALL),
        (Pos(9, 9), PointType.WALL),
        (Pos(9, 10), PointType.WALL),
        (Pos(8, 10), PointType.WALL),
        (Pos(8, 9), PointType.WALL),
        (Pos(8, 8), PointType.WALL),
        (Pos(8, 7), PointType.WALL),
        (Pos(8, 6), PointType.WALL),
        (Pos(7, 6), PointType.WALL),
        (Pos(7, 7), PointType.WALL),
        (Pos(7, 8), PointType.WALL),
        (Pos(7, 9), PointType.WALL),
        (Pos(7, 10), PointType.WALL)
    )